version: 2
updates:
  # dependabot is able to update `Package.resolved`. But renovate isn't.
  # So trying to use both.
  - package-ecosystem: "swift"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#github-actions
    # > Docker Hub and GitHub Packages Container registry URLs are currently not supported.
    # So using renovate instead.
    open-pull-requests-limit: 0
