name: CI

on:
  push:
    branches: [main, wasm]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: swift test --enable-code-coverage
      - name: llvm-cov export
        run: |
          xcrun llvm-cov export \
            .build/debug/swift-local-datePackageTests.xctest/Contents/MacOS/swift-local-datePackageTests \
            -format=lcov \
            -instr-profile .build/debug/codecov/default.profdata \
            > .build/debug/codecov/info.lcov
      - uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift:
          - 5.7
          - 5.8
          - 5.9
    container: swift:${{ matrix.swift }}
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: swift test

  benchmark:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run benchmark
        run: swift run -c release swift-local-date-benchmark

  wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bytecodealliance/actions/wasmtime/setup@v1
      - uses: swiftwasm/setup-swiftwasm@v1
        with:
          swift-version: "wasm-5.9.2-RELEASE"
      - name: Build tests
        run: swift build --triple wasm32-unknown-wasi --build-tests
        # run: swift build --triple wasm32-unknown-unknown --target LocalDateTests
      - name: Run tests
        run: wasmtime .build/debug/swift-local-datePackageTests.wasm
